services:
  xinference:
    image: biocypher/xinference-builtin:0.0.0
    container_name: xinference_builtin
    build: .
    command: bash launch_script.sh
    restart: always
    env_file:
      - zephyr-7b-beta.env
      # - llama-2-13b.env
    ports:
      - "9997:9997"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
